name: Test
on:
  push:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Rust
        run: cargo build
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Dependencies
        run: yarn --cwd svelte install
      - name: Build Svelte
        run: yarn --cwd svelte run build
      - name: Run Tests
        run: cargo test